### ISSUE TITLE
Modifying the ctree after certain events may lead to crash

### ISSUE THREAD

**Issue by patois** [patois/abyss#4]
WIP

**Comment by x64bugreport** [comment]
The plug-in works very well. When will you fix this bug?

**Comment by x64bugreport** [comment]
Traceback (most recent call last):
  File "G:/IDA75/plugins/abyss.py", line 152, in text_ready
    obj.process_text(vu)
  File "G:/IDA75/plugins\abyss_filters\ctopy.py", line 1331, in process_text
    lines = "\n".join([ida_lines.tag_remove(sl.line) for sl in pc])
  File "G:/IDA75/plugins\abyss_filters\ctopy.py", line 1331, in <listcomp>
    lines = "\n".join([ida_lines.tag_remove(sl.line) for sl in pc])
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 204: invalid start byte

**Comment by patois** [comment]
> 
> 
> The plug-in works very well. When will you fix this bug?

As far as I can recall, this issue is related to hooking print_func() of the hx_event_t class and modifying the ctree itself inside of it.
Unfortunately, I did not have the time yet to look into it in detail. The abyss "lvars_alias.py" and "lvars_info.py" filters/plugins rely on it. As long as you did not experience any problems with it, you can safely ignore this bug tho.

**Comment by patois** [comment]
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 204: invalid start byte

This seems to be an unrelated/different issue. I'd recommend opening a new issue. If you do, could you please describe how to reproduce this issue? Which service pack of IDA 7.5 are you using exactly? What does the original decompiled text look like before it is processed by abyss?
I suspect it may even be a problem with IDAPython itself since ctopy doesn't directly call the decode() method.

**Comment by x64bugreport** [comment]
IDA 7.5 SP2 with PYTHON 3.8.6
The problem may be caused by a pseudo-code page that contains comments.
